name: vcftools
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - sra-tools >2.9.1
    - pigz =2.6
    - pbzip2 =1.1
    - trimmomatic ==0.36
    - fastqc ==0.11.9
    - multiqc ==1.10.1
    - salmon ==1.5.1
    - vcftools == 0.1.16

