name: Testing notebooks with nbmake

on:
  workflow_dispatch: 
  #push:
  #  branches:
  #    - "*"
  #pull_request:
  #  branches:
  #    - "*"

jobs:
  test-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install jupyter
        pip install pytest nbmake nbformat
        ## Later move the above to a requrements.txt and run the below
        ## pip install -r requirements.txt 

    - name: Setup required variables
      env:
        NOTEBOOK_GCP_PROJECT_ID: ${{ secrets.NOTEBOOK_GCP_PROJECT_ID }}
        NOTEBOOK_GCP_LOCATION: ${{ secrets.NOTEBOOK_GCP_LOCATION }}
      run: |
        echo "NOTEBOOK_GCP_PROJECT_ID=${NOTEBOOK_PROJECT_ID}" >> $GITHUB_ENV
        echo "NOTEBOOK_GCP_LOCATION=${NOTEBOOK_GCP_LOCATION}" >> $GITHUB_ENV
        
    - name: Test notebook
      run: |
        pwd
        #jupyter nbconvert --to notebook --execute notebooks/GenAI/Gemini_Intro.ipynb
        pytest --nbmake notebooks/GenAI/Gemini_Intro.ipynb --variable-file=env.json
        
